# Generated by Django 5.0.2 on 2024-03-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(upload_to='')),
                ('facebook_page', models.CharField(max_length=100)),
                ('instagram_page', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=100)),
                ('cta_title', models.CharField(max_length=100)),
                ('cta_description', models.TextField()),
                ('cta_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('client_name', models.CharField(max_length=50)),
            ],
        ),
    ]
