# Generated by Django 5.0.2 on 2024-03-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='hero_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
